# Generated by Django 4.1.5 on 2023-01-24 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_remove_user_follows_userfollows"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followed_members",
            field=models.ManyToManyField(
                related_name="followed",
                through="authentication.UserFollows",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
