# Generated by Django 4.1.5 on 2023-02-12 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0004_alter_review_ticket_alter_review_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="time_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
