# Generated by Django 4.1.5 on 2023-02-17 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0005_review_time_created"),
    ]

    operations = [
        migrations.RemoveField(model_name="review", name="id",),
        migrations.AddField(
            model_name="ticket",
            name="with_review",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="review",
            name="ticket",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="reviews",
                serialize=False,
                to="feed.ticket",
            ),
        ),
    ]
