# Generated by Django 4.1.5 on 2023-02-20 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0006_remove_review_id_ticket_with_review_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="ticket", name="with_review",),
        migrations.AddField(
            model_name="review",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="feed.ticket",
            ),
        ),
    ]
