# Generated by Django 4.1.5 on 2023-02-20 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0007_remove_ticket_with_review_review_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="ticket",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="feed.ticket",
            ),
        ),
    ]
