# Generated by Django 4.1.5 on 2023-02-20 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0008_alter_review_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="ticket",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_review",
                to="feed.ticket",
            ),
        ),
    ]
